<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Ascentry.E2E</RootNamespace>
	  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	  <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Core\Translations\fr-FR.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.9" />
    <PackageReference Include="Microsoft.Playwright" Version="1.61.0" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" />
  </ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Core\Translations\*.json" />
	</ItemGroup>

  <ItemGroup>
    <None Include="Core\Translations\TranslationProvider.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ascentry.E2E.Contracts\Ascentry.E2E.Contracts.csproj" />
  </ItemGroup>

</Project>
